/**********************************************************************************************************************
 * \file setPoint.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "setPoint.h"
#include "ComOutput.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
int GetGnssDataTimes = 20;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
uint8 ButtonPushed(gpio_pin_enum pin){
    return !gpio_get_level(pin);
}

/*
 * @brief 打点
 *
 * @param Point 数据记录进的位置
 *
 * @retval 目前记录的点数
 * @note 注意 index 超过 MAX_POINTS 时会从头计数
*/
int SetPoint(GnssData Point[MAX_POINTS]){
    static int index = 0;

    if (index >= MAX_POINTS){
        uart_write_string(DEBUG_UART_INDEX, "Point array overflow! Current count: ");
        uart_write_integer(DEBUG_UART_INDEX, index);
        uart_write_string(DEBUG_UART_INDEX, "\n");
        index = 0;
    }

    double latitude = 0;
    double longitude = 0;
    float speed = 0;
    float direction = 0;

//    for (int i = 0; i < GetGnssDataTimes; i ++ ){
//        if (gnss_flag){
//            gnss_flag = 0;
//            gnss_data_parse();
//
//            latitude += gnss.latitude;
//            longitude += gnss.longitude;
//            speed += gnss.speed;
//            direction += gnss.direction;
//        }
//        else{ // 回退
//            i --;
//        }
//    }
//    Point[index].longitude = longitude / GetGnssDataTimes;
//    Point[index].latitude = latitude / GetGnssDataTimes;
//    Point[index].speed = speed / GetGnssDataTimes;
//    Point[index].direction = direction / GetGnssDataTimes;

    while (true){
        if (gnss_flag){
            gnss_flag = 0;
            gnss_data_parse();
            Point[index].longitude = gnss.longitude;
            Point[index].latitude = gnss.latitude;
            Point[index].speed = gnss.speed;
            Point[index].direction = gnss.direction;
            uart_write_string(DEBUG_UART_INDEX, "Valid Data\n");
            break;
        }
        else{
            uart_write_printf(DEBUG_UART_INDEX, "Invalid data!\n");
            system_delay_ms(100);
        }
    }

    // 现在要计算 这个点和上一个点之间的距离和角度了
    if (index == 0) // 第一个点
        return index;

    Point[index].DegreeToNextNode = get_two_points_azimuth(
            Point[index - 1].latitude, Point[index - 1].longitude,
            Point[index].latitude, Point[index].longitude);
    Point[index].DistanceToNextNode = get_two_points_distance(
            Point[index - 1].latitude, Point[index - 1].longitude,
            Point[index].latitude, Point[index].longitude);

    char str[140] = {0};
    sprintf(str,
            "index=%d, longitude=%.4lf, latitude=%.4lf, speed=%.4f, direction=%.4f, DisToNextNode=%.4lf, DegToNextNode=%.4lf\n",
            index, Point[index].longitude, Point[index].latitude, Point[index].speed, Point[index].direction, Point[index].DistanceToNextNode, Point[index].DegreeToNextNode);
    index ++;

    // send messages
    uart_write_string(DEBUG_UART_INDEX, str);

    return index;
}
/*********************************************************************************************************************/
