################################################################################
# 自动生成的文件。不要编辑！
################################################################################

BLOCKING_ERROR = No AURIX device is configured in this project. The project may have been created with an old version of AURIX Development Studio. The project is not supported

clean:
all:
	@echo $(BLOCKING_ERROR)
	@exit
