/**********************************************************************************************************************
 * \file ComOutput.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "ComOutput.h"
#include <stdarg.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
int OUTPUT_MAX_LENGTH = 140;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*
 * @brief 向指定串口打印 整数
 *
 * @param uart_n 指定串口 Eg. DEBUG_UART_INDEX
 * @param num 要输出的数字
 */
void uart_write_integer(uart_index_enum uart_n, uint16 num){
    char str[31] = {0};
    sprintf(str, "%hu", num);
    int len = strlen(str);
    for (short i = 0; i < len; i ++){
        uart_write_byte(uart_n, str[i]);
    }
}

/*
 * @brief 向指定串口打印 float 类型的小数
 *
 * @param uart_n 指定串口 Eg. DEBUG_UART_INDEX
 * @param num 要输出的数字
 */
void uart_write_float(uart_index_enum uart_n, float num){
    char str[31] = {0};
    sprintf(str, "%f", num);
    for (short i = 0; i < strlen(str); i++){
        uart_write_byte(uart_n, str[i]);
    }
}

/*
 * @brief 向指定串口打印指定内容
 *
 * @param uart_n 指定的串口 Eg. DEBUG_UART_INDEX
 * @param format 需要打印的内容
 *
 * @note 使用此函数就像 printf 一样 只不过最前面需要加上串口
 * @note STILL IN DEBUG MODE!
 */
void uart_write_printf(uart_index_enum uart_n, const char* format, ...){
    char str[OUTPUT_MAX_LENGTH];
    va_list args;
    va_start(args, format);
    vsnprintf(str, OUTPUT_MAX_LENGTH, format, args);
    uart_write_string(uart_n, str);
    va_end(args);
}

/*********************************************************************************************************************/
