################################################################################
# 鑷姩鐢熸垚鐨勬枃浠躲�備笉瑕佺紪杈戯紒
################################################################################

C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SRC_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
COMPILED_SRCS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 

# 姝ゅ蹇呴』鎻忚堪鍖呭惈婧愭枃浠剁殑姣忎釜瀛愮洰褰�
SUBDIRS := \
Configurations/Debug \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Math \
Libraries/iLLD/TC26B/Tricore/Asclin/Asc \
Libraries/iLLD/TC26B/Tricore/Asclin/Lin \
Libraries/iLLD/TC26B/Tricore/Asclin/Spi \
Libraries/iLLD/TC26B/Tricore/Asclin/Std \
Libraries/iLLD/TC26B/Tricore/Ccu6/Icu \
Libraries/iLLD/TC26B/Tricore/Ccu6/PwmBc \
Libraries/iLLD/TC26B/Tricore/Ccu6/PwmHl \
Libraries/iLLD/TC26B/Tricore/Ccu6/Std \
Libraries/iLLD/TC26B/Tricore/Ccu6/TPwm \
Libraries/iLLD/TC26B/Tricore/Ccu6/Timer \
Libraries/iLLD/TC26B/Tricore/Ccu6/TimerWithTrigger \
Libraries/iLLD/TC26B/Tricore/Cif/Cam \
Libraries/iLLD/TC26B/Tricore/Cif/Std \
Libraries/iLLD/TC26B/Tricore/Cpu/CStart \
Libraries/iLLD/TC26B/Tricore/Cpu/Irq \
Libraries/iLLD/TC26B/Tricore/Cpu/Std \
Libraries/iLLD/TC26B/Tricore/Cpu/Trap \
Libraries/iLLD/TC26B/Tricore/Dma/Dma \
Libraries/iLLD/TC26B/Tricore/Dma/Std \
Libraries/iLLD/TC26B/Tricore/Dsadc/Dsadc \
Libraries/iLLD/TC26B/Tricore/Dsadc/Rdc \
Libraries/iLLD/TC26B/Tricore/Dsadc/Std \
Libraries/iLLD/TC26B/Tricore/Dts/Dts \
Libraries/iLLD/TC26B/Tricore/Dts/Std \
Libraries/iLLD/TC26B/Tricore/Emem/Std \
Libraries/iLLD/TC26B/Tricore/Eray/Eray \
Libraries/iLLD/TC26B/Tricore/Eray/Std \
Libraries/iLLD/TC26B/Tricore/Eth/Phy_Pef7071 \
Libraries/iLLD/TC26B/Tricore/Eth/Std \
Libraries/iLLD/TC26B/Tricore/Fce/Crc \
Libraries/iLLD/TC26B/Tricore/Fce/Std \
Libraries/iLLD/TC26B/Tricore/Fft/Fft \
Libraries/iLLD/TC26B/Tricore/Fft/Std \
Libraries/iLLD/TC26B/Tricore/Flash/Std \
Libraries/iLLD/TC26B/Tricore/Gpt12/IncrEnc \
Libraries/iLLD/TC26B/Tricore/Gpt12/Std \
Libraries/iLLD/TC26B/Tricore/Gtm/Atom/Pwm \
Libraries/iLLD/TC26B/Tricore/Gtm/Atom/PwmHl \
Libraries/iLLD/TC26B/Tricore/Gtm/Atom/Timer \
Libraries/iLLD/TC26B/Tricore/Gtm/Std \
Libraries/iLLD/TC26B/Tricore/Gtm/Tim/In \
Libraries/iLLD/TC26B/Tricore/Gtm/Tom/Pwm \
Libraries/iLLD/TC26B/Tricore/Gtm/Tom/PwmHl \
Libraries/iLLD/TC26B/Tricore/Gtm/Tom/Timer \
Libraries/iLLD/TC26B/Tricore/Gtm/Trig \
Libraries/iLLD/TC26B/Tricore/Hssl/Hssl \
Libraries/iLLD/TC26B/Tricore/Hssl/Std \
Libraries/iLLD/TC26B/Tricore/I2c/I2c \
Libraries/iLLD/TC26B/Tricore/I2c/Std \
Libraries/iLLD/TC26B/Tricore/Iom/Driver \
Libraries/iLLD/TC26B/Tricore/Iom/Std \
Libraries/iLLD/TC26B/Tricore/Msc/Msc \
Libraries/iLLD/TC26B/Tricore/Msc/Std \
Libraries/iLLD/TC26B/Tricore/Mtu/Std \
Libraries/iLLD/TC26B/Tricore/Multican/Can \
Libraries/iLLD/TC26B/Tricore/Multican/Std \
Libraries/iLLD/TC26B/Tricore/Port/Io \
Libraries/iLLD/TC26B/Tricore/Port/Std \
Libraries/iLLD/TC26B/Tricore/Psi5/Psi5 \
Libraries/iLLD/TC26B/Tricore/Psi5/Std \
Libraries/iLLD/TC26B/Tricore/Psi5s/Psi5s \
Libraries/iLLD/TC26B/Tricore/Psi5s/Std \
Libraries/iLLD/TC26B/Tricore/Qspi/SpiMaster \
Libraries/iLLD/TC26B/Tricore/Qspi/SpiSlave \
Libraries/iLLD/TC26B/Tricore/Qspi/Std \
Libraries/iLLD/TC26B/Tricore/Scu/Std \
Libraries/iLLD/TC26B/Tricore/Sent/Sent \
Libraries/iLLD/TC26B/Tricore/Sent/Std \
Libraries/iLLD/TC26B/Tricore/Smu/Std \
Libraries/iLLD/TC26B/Tricore/Src/Std \
Libraries/iLLD/TC26B/Tricore/Stm/Std \
Libraries/iLLD/TC26B/Tricore/Stm/Timer \
Libraries/iLLD/TC26B/Tricore/Vadc/Adc \
Libraries/iLLD/TC26B/Tricore/Vadc/Std \
Libraries/iLLD/TC26B/Tricore/_Impl \
Libraries/iLLD/TC26B/Tricore/_Lib/DataHandling \
Libraries/iLLD/TC26B/Tricore/_Lib/InternalMux \
Libraries/iLLD/TC26B/Tricore/_PinMap \
keyu_library/common \
keyu_library/core \
keyu_library/devices \
keyu_library/drivers \
main \

