/*********************************************************************************************************************
* TC264 Opensource Library (TC264 Open Source Library) is a set of source code for official SDK interfaces
* Copyright (c) 2022 SEEKFREE Inc.
*
* This file is part of the TC264 Open Source Library
*
* TC264 Open Source Library Usage Terms
* You may use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following:
* The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
* For more details, see GPL
*
* If you distribute the source code, you must also distribute a copy of the GPL license
* You can find it at <https://www.gnu.org/licenses/>
*
* Important Notes
* This source code uses GPL3.0 open source license agreement, and we consider this version to be stable
* For English version of the license, see GPL3_permission_statement.txt in libraries/doc folder
* For license details, see LICENSE file in libraries folder
* Welcome to use and modify this code. When modifying, please keep the SEEKFREE copyright and license information
*
* File Name          cpu0_main
* Company Name       SEEKFREE Inc.
* Version Info       See version file in libraries/doc folder for version description
* Development Env    ADS v1.10.2
* Platform           TC264D
* Official Website   https://seekfree.taobao.com/
*
* Modification Log
* Date               Author              Notes
* 2022-09-15         pudding             first version
********************************************************************************************************************/
#include "zf_common_headfile.h"
#include "zf_device_gnss.h"
#include <stdbool.h>
#include "ComOutput.h"
#include "setPoint.h"
#include "motor_pid.h"
#include "angle_control.h"
#pragma section all "cpu0_dsram"
// All global variables after #pragma section all restore are placed in CPU0 RAM

// For future expansion, do not modify these lines
// For future expansion, do not modify these lines
// For future expansion, do not modify these lines

// typedef unsigned short uint16;
//
//#define KEY1                    (P20_6)
//#define KEY2                    (P20_7)
//#define KEY3                    (P11_2)
//#define KEY4                    (P11_3)

void IPS200_Show_Init(void)
{
    ips200_set_color(RGB565_BLACK, RGB565_WHITE);    // Set color to black background white text
    ips200_set_font(IPS200_6X8_FONT);    // Set font size to 6 * 8
    ips200_set_dir(IPS200_PORTAIT);    // Set display direction to portrait
    ips200_init(IPS200_TYPE_SPI);    // Set communication mode to SPI
}

#define MAX_POINTS 30

GnssData Point[MAX_POINTS];
int index = 0;

// **********************+****** Main Function ****************************
int core0_main(void)
{
    clock_init();                   // Get clock frequency <do not modify>
    debug_init();                   // Initialize default debug output
    // Write user initialization code here

     gnss_init(GN42A);
    //    bool parse = false;
    //    ips200_init(IPS200_TYPE_PARALLEL8);
    //
    //    ips200_clear();
    //     IPS200_Show_Init();
    uint16 count = 0;

    gpio_init(KEY1, GPI, GPIO_HIGH, GPI_PULL_UP);           // Initialize KEY1 pin, default high level, pull-up
    gpio_init(KEY2, GPI, GPIO_HIGH, GPI_PULL_UP);           // Initialize KEY2 pin, default high level, pull-up
    gpio_init(KEY3, GPI, GPIO_HIGH, GPI_PULL_UP);           // Initialize KEY3 pin, default high level, pull-up
    gpio_init(KEY4, GPI, GPIO_HIGH, GPI_PULL_UP);           // Initialize KEY4 pin, default high level, pull-up
    




    //pid控制占空比，使电机定速转动
    motor_pid_init(MOTOR_DEFAULT_KP, MOTOR_DEFAULT_KI, MOTOR_DEFAULT_KD);
    pit_init(CCU60_CH0, 10 * 1000); // 10ms PIT timer
    motor_pid_set_target(250); // Set target speed to 50% of max speed
    
    
    //角度电机转动
    angle_control_init();
    angle_control_set_target(360); // Set angle target to 360 degrees






    cpu_wait_event_ready();         // Wait for all core initialization to complete

    int index = 0;
    while (TRUE)
    {


//        if (index > 150)
//            index = 0;
//        index ++;
//        uart_write_printf(DEBUG_UART_INDEX, "Current Index = %d, Great!\n", index);
//        system_delay_ms(500);

        // TODO: Add code here
        if ((ButtonPushed(KEY1) || ButtonPushed(KEY2) || ButtonPushed(KEY3) || ButtonPushed(KEY4))){
            // If button pressed, get 20 GPS points and average
            SetPoint(Point);

            system_delay_ms(500);
        }
        system_delay_ms(20);

//        if (gnss_flag){
//            gnss_flag = 0;
//            gnss_data_parse();
//        }
//        else{
//            uart_write_string(DEBUG_UART_INDEX, "GPS data invalid! Point array is disabled...\n");
//            system_delay_ms(500);
//            continue;
//        }
//

//        uart_write_string(DEBUG_UART_INDEX, "I am still working!\n");
//        system_delay_ms(50);

//        if (!gpio_get_level(KEY1)){
//            // P20_6 pressed
//            if (index >= MAX_POINTS){
//                index = 0;
//                uart_write_string(DEBUG_UART_INDEX, "Point array overflow! Current count: ");
//                uart_write_integer(DEBUG_UART_INDEX, index);
//                uart_write_string(DEBUG_UART_INDEX, "\n");
//            }
//            Point[index].longitude = gnss.longitude;
//            Point[index].latitude = gnss.latitude;
//            Point[index].speed = gnss.speed;
//            Point[index].direction = gnss.direction;
//            index ++;
//        }


//         if (gnss_flag) {
//             gnss_flag = 0;
//             count = 0;
//             gnss_data_parse();
//
//             uart_write_float(DEBUG_UART_INDEX, gnss.direction);
//             uart_write_string(DEBUG_UART_INDEX, "Direction Got!\n");
//         }
//         else {
//             count++;
//             if (count % 10 == 0) {
//                 uart_write_string(DEBUG_UART_INDEX, "Current Count: ");
//                 uart_write_integer(DEBUG_UART_INDEX, count);
//                 uart_write_string(DEBUG_UART_INDEX, ", Wait for data...\n");
//             }
//         }

        // 閿熷壙杈炬嫹閿熸枻鎷峰啓閿熸枻鎷疯寰敓鏂ゆ嫹鎵ч敓鍙殑杈炬嫹閿熸枻鎷?
    }
}

#pragma section all restore
// **************************** 閿熸枻鎷烽敓鏂ゆ嫹閿熸枻鎷烽敓鏂ゆ嫹 ****************************
